### Slow in processing pdf
@idvTransaction_id=cf5f108a-7230-4c90-be14-80738f06c57d

get {{customer-url}}/api/transaction/{{idvTransaction_id}}/document/AuditTrailDocument/pdf HTTP/1.1
Authorization: Bearer {{token}}

