### Slow in processing pdf
@idvTransaction_id=b0c91851-830d-41f1-9dea-751852b29f34

get {{customer-url}}/api/transaction/{{idvTransaction_id}}/document/AuditTrailDocument/pdf HTTP/1.1
Authorization: Bearer {{token}}



TXARRAY=( "dafe4721-1cfd-4278-80b4-eae91a33b229" )

./at_on_demand.sh
--url
--token
--tx
--name $TXARRAY