###  Tried and does set transaction to a cancelled status
@idvTransaction_id=1ae787bc-2482-43da-9630-812764dc9a7a

put {{customer-url}}/api/transaction/{{idvTransaction_id}}/event
Authorization: Bearer {{token}}
Content-Type: application/json

{
"trigger": "transaction_cancelled"
}