### will create a transaction - **** DO IN SANDBOX ONLY **** 
// LOGS IDV_EU_Externasl

// https://idvgl006.uat.eu01.idv.onespan.cloud/IDVerification/BtmV6SHafA8VK7ZAFV5eKO
// b0c91851-830d-41f1-9dea-751852b29f34

put {{customer-url}}/api/transaction/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "workflow_id": "8d52e695-daea-4aad-9875-ef3b70f5febc",
  "language": "en",
  "brand_id": "idvgl006brd01",
  "opaque_id": "WorkflowExternalMitAt1234",
  "users": [{
    "groups":["visible"],
    "first_name": "John",
    "middle_name": "Paul",
    "last_name": "McGuinness",
    "title": "Mr",
    "role": "Customer",
    "phone_number": "+447485213049",
    "dob": "1904-01-01T00:00:00.000Z",
    "address": {
      "country_code": "GB"
        }
    }
  ],
  "tokens": [
    {
      "role": "Customer"
    }
  ],
   "configuration":{
        "redirects": [
            {
                "id": "REDIRECT_SESSION_TIMEOUT",
                "url": "https://bov.bovplusappretail.com/?user=Customer&transaction=52f56d55-0a5c-469b-9a21-a41e34433bcc&opaqueId=WorkflowExternalMitAt1234&deviceId=669601a3-09bc-4b47-9c69-34e3573f3637"
            },
            {
                "id": "REDIRECT_DEFAULT_URL",
                "url": "https://bov.bovplusappretail.com/?user=Customer&transaction=52f56d55-0a5c-469b-9a21-a41e34433bcc&opaqueId=WorkflowExternalMitAt1234&deviceId=669601a3-09bc-4b47-9c69-34e3573f3637"
            },
            {
                "id": "REDIRECT_DOCID_PASS",
                "url": "https://bov.bovplusappretail.com/?user=Customer&transaction=52f56d55-0a5c-469b-9a21-a41e34433bcc&opaqueId=WorkflowExternalMitAt1234&deviceId=669601a3-09bc-4b47-9c69-34e3573f3637"
            },
            {
                "id": "REDIRECT_ERROR",
                "url": "https://bov.bovplusappretail.com/?user=Customer&transaction=52f56d55-0a5c-469b-9a21-a41e34433bcc&opaqueId=WorkflowExternalMitAt1234&deviceId=669601a3-09bc-4b47-9c69-34e3573f3637"
            },
            {
                "id": "REDIRECT_DOCID_FAIL",
                "url": "https://bov.bovplusappretail.com/?user=Customer&transaction=52f56d55-0a5c-469b-9a21-a41e34433bcc&opaqueId=WorkflowExternalMitAt1234&deviceId=669601a3-09bc-4b47-9c69-34e3573f3637"
            }
        ]
    }
}


// https://idvgl006.uat.eu01.idv.onespan.cloud/IDVerification/GBmZoVf6Xv5089TERUPjwt
// bfabe7f4-2c7e-486c-bbfd-152b8440f77c - cancelled
// https://idvgl006.uat.eu01.idv.onespan.cloud/IDVerification/F7DKSeJGR4cZ3AdNBtQjk9
// 1ae787bc-2482-43da-9630-812764dc9a7a - cancelled
// https://idvgl006.uat.eu01.idv.onespan.cloud/IDVerification/HvM2mHNJWcCHwTJzenE0IJ
// 124f700d-2e9d-464f-9410-306d3bc13be7 - cancelled
// https://idvgl006.uat.eu01.idv.onespan.cloud/IDVerification/BXrVuFunC0rcN89sV7uuZF
// dafe4721-1cfd-4278-80b4-eae91a33b229 - completed and failed