### Download image binary data
@idvTransaction_id=b0c91851-830d-41f1-9dea-751852b29f34
@sfs_url=sfs://vhub-default/default/ONESPAN_IDV_LIVE/transactions/23d28db6-424c-47ed-a067-04984bcefba2/biometrics/0f3d7f12-103d-4f1d-b234-87d53d2a1c50/1.png

get {{customer-url}}/api/transactions/{{idvTransaction_id}}/data?url={{sfs_url}}
Authorization: Bearer {{token}}