### 
post {{customer-url}}/api/transactions/mark-for-erasure
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "grace_period": 25,
    "transaction_ids": [
        "124f700d-2e9d-464f-9410-306d3bc13be7"
    ]
}

###
post {{customer-url}}/api/transactions/unmark-for-erasure
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "grace_period": 25,
    "transaction_ids": [
        "xxxxx-xxxxx-xxxxx-xxxxxx",
        "xxxxx-xxxxx-xxxxx-xxxxxx"
    ]
}
